### ISSUE TITLE
if there is an ingredient removed from the fridge, the cooking today's missing ingredient is not updated

### ISSUE THREAD

**Issue by rafs-potato** [favian-cyril/BitFridge#28]
1. add 'milk' to fridge
2. add 'chocolate oatmeal' to cooking today
3. add any other recipe (added 'hot coated fish' and 'panna cotta ganache')
4. ingredient list in cooking today for 'chocolate oatmeal' contains 'rolled oats' and 'cocoa powder'
5. add 'cocoa powder' to fridge
6. the cooking today's missing ingredient updated, no longer contains 'cocoa powder'
7. remove 'cocoa powder' from fridge
8. the cooking today's missing ingredients only shows 'rolled oats'
![image](https://cloud.githubusercontent.com/assets/16080118/20483876/0a6dc8c8-b027-11e6-9e25-7183b35894fa.png)

**Comment by favian-cyril** [comment]
fixed
