### ISSUE TITLE
not all ingredients are listed

### ISSUE THREAD

**Issue by rafs-potato** [favian-cyril/BitFridge#30]
e.g:
in bitfridge, the ingredients needed for the naan are 'milk', 'baking powder' and 'baking soda'
![image](https://cloud.githubusercontent.com/assets/16080118/20484703/1273657e-b02b-11e6-90ba-9c321c036caa.png)

but if we go to the recipe page we could see that we actually need:
'flour', 'salt', 'baking powder',  ' baking soda',  'canola oil', and 'milk'
 
![image](https://cloud.githubusercontent.com/assets/16080118/20484788/7096f45e-b02b-11e6-81ca-08591ae57251.png)

this also happens with many other recipes. usually the one which need 'flour'

**Comment by chadmadna** [comment]
This comes from the limitations of the Spoonacular API. Not in our domain, closing issue.
