### ISSUE TITLE
Fridge ingredients remove button not tidy

### ISSUE THREAD

**Issue by rafs-potato** [favian-cyril/BitFridge#9]
![berantakan](https://cloud.githubusercontent.com/assets/16080118/20027868/7337ae5e-a353-11e6-98f4-bfcf7cd4aabf.PNG)

this will happen if there are a long named ingredients and when there are more than 4 ingredients in the fridge (the button still works normally)

**Comment by chadmadna** [comment]
Fixed in 0d4afc449d4e263576e7f416bba910abe35a5a7b.
